[project]
name = "video-splitter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.4",
    "pathlib>=1.0.1",
    "psycopg2-binary>=2.9.10",
    "psycopg2>=2.9.10",
    "python-dotenv>=1.0.1",
    "pytubefix>=8.3.0",
    "sqlmodel>=0.0.22",
    "supabase>=2.10.0",
]
